version: "3.9"

services:
  open-source-health-dashboard:
    build: .
    ports:
      - "4008:4008"
    environment:
      - PORT=4008
    # Remove volumes in production so the build is used
    # volumes:
    #   - ./server:/app/server
    #   - ./client:/app/client